[package]
name = "kjv_redis"
version = "0.1.0"
authors = ["danebalia <dane.balia@sourcing-sa.co.za>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[dependencies.redis]
version = "*"
